version: '3'

# this override should be used along with an .env file like this:
# DBDUMP_S3_ACCESS=
# DBDUMP_S3_SECRET=
# DBDUMP_S3_FILE_PREFIX=testing_
# S3_RESTORE_ACCESS=
# S3_RESTORE_SECRET=
# S3_RESTORE_FILENAMES=2020-06-07_14-45-20_anyway_roles 2020-06-07_14-45-24_anyway_schema 2020-06-07_14-45-27_anyway_data
# S3_RESTORE_ANYWAY_PASSWORD=12345678
# POSTGRES_PASSWORD=123456
# POSTGRES_USER=
# POSTGRES_DB=
# DATABASE_URL=postgresql://anyway:12345678@db/anyway

services:
  nginx:
    build: nginx_docker
    image: anywayteam/nginx:latest
    depends_on:
      - anyway
    ports:
      - "8000:80"

  anyway:
    environment:
      - DATABASE_URL
    command: "gunicorn -b 0.0.0.0:8000 -w 4 -t 120 anyway:app"

  db:
    environment:
      - S3_RESTORE_ACCESS
      - S3_RESTORE_SECRET
      - S3_RESTORE_FILENAMES
      # this is the password for postgres user, not for anyway user
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      # this is the password for anyway user, it will be set on initial restore only
      - S3_RESTORE_ANYWAY_PASSWORD

  db-backup:
    build:
      context: db_docker
      dockerfile: backup.Dockerfile
    environment:
      - DBDUMP_S3_ACCESS
      - DBDUMP_S3_SECRET
      - DBDUMP_S3_FILE_PREFIX
      - DBDUMP_HOST=db
      - DBDUMP_DB=anyway
      - DBDUMP_USER=anyway
      - DBDUMP_PASSWORD=anyway
    restart: "no"
