version: '3'

services:
  anyway:
    build: .
    image: anywayteam/anyway:latest
    container_name: anyway
    ports:
      - "8080:5000"
    environment:
      - DATABASE_URL=postgresql://anyway:anyway@db/anyway
    volumes:
      - .:/anyway
    restart: always
    depends_on:
      - db

  db:
    build: db_docker
    image: anywayteam/db:latest
    container_name: db
    environment:
      - GDRIVE_FILE_ID
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "9876:5432"
    restart: always

volumes:
  db_data:
